/**
 * Physical / spell weapon-only affix pools (design: docs/design/06-equipment.md 7.3).
 * Merged with AFFIX_POOL in equipment.js when rolling magic/rare weapons.
 * ASCII ids; display names use Unicode escapes.
 */

export const PHYS_WEAPON_AFFIX_POOL = [
  { id: 'phys-fierce-n', name: '\u731b\u5217', type: 'prefix', tier: 'normal', baseMin: 2, baseMax: 6, stat: 'physWeaponFlat' },
  { id: 'phys-fierce-e', name: '\u51f6\u731b', type: 'prefix', tier: 'exceptional', baseMin: 8, baseMax: 20, stat: 'physWeaponFlat' },
  { id: 'phys-fierce-l', name: '\u6b8b\u66b4', type: 'prefix', tier: 'elite', baseMin: 20, baseMax: 45, stat: 'physWeaponFlat' },
  { id: 'phys-sharp-n', name: '\u9510\u5229', type: 'prefix', tier: 'normal', baseMin: 2, baseMax: 4, stat: 'physCritPct' },
  { id: 'phys-sharp-e', name: '\u9510\u9510', type: 'prefix', tier: 'exceptional', baseMin: 4, baseMax: 8, stat: 'physCritPct' },
  { id: 'phys-sharp-l', name: '\u5251\u5203', type: 'prefix', tier: 'elite', baseMin: 8, baseMax: 15, stat: 'physCritPct' },
  { id: 'phys-crushing-n', name: '\u538b\u788e', type: 'prefix', tier: 'normal', baseMin: 4, baseMax: 10, stat: 'physCritDmgPct' },
  { id: 'phys-crushing-e', name: '\u6bc1\u706d', type: 'prefix', tier: 'exceptional', baseMin: 10, baseMax: 22, stat: 'physCritDmgPct' },
  { id: 'phys-crushing-l', name: '\u6bc1\u7cbe', type: 'prefix', tier: 'elite', baseMin: 22, baseMax: 40, stat: 'physCritDmgPct' },
  { id: 'phys-vamp-n', name: '\u5438\u8840', type: 'prefix', tier: 'normal', baseMin: 2, baseMax: 4, stat: 'lifeStealPct' },
  { id: 'phys-vamp-e', name: '\u9965\u6e34', type: 'prefix', tier: 'exceptional', baseMin: 4, baseMax: 8, stat: 'lifeStealPct' },
  { id: 'phys-vamp-l', name: '\u55dc\u9b42', type: 'prefix', tier: 'elite', baseMin: 8, baseMax: 14, stat: 'lifeStealPct' },
  { id: 'phys-siphon-n', name: '\u6d41\u8f6c', type: 'prefix', tier: 'normal', baseMin: 3, baseMax: 8, stat: 'lifeOnHit' },
  { id: 'phys-siphon-e', name: '\u7f1d\u5408', type: 'prefix', tier: 'exceptional', baseMin: 8, baseMax: 18, stat: 'lifeOnHit' },
  { id: 'phys-siphon-l', name: '\u6ecb\u517b', type: 'prefix', tier: 'elite', baseMin: 18, baseMax: 35, stat: 'lifeOnHit' },
  { id: 'phys-imbue-n', name: '\u9644\u9b54', type: 'prefix', tier: 'normal', baseMin: 4, baseMax: 10, stat: 'addedMagicDmg' },
  { id: 'phys-imbue-e', name: '\u5143\u7d20', type: 'prefix', tier: 'exceptional', baseMin: 10, baseMax: 22, stat: 'addedMagicDmg' },
  { id: 'phys-imbue-l', name: '\u4f4d\u9762', type: 'prefix', tier: 'elite', baseMin: 22, baseMax: 45, stat: 'addedMagicDmg' },
  { id: 'phys-penet-n', name: '\u7a7f\u900f', type: 'prefix', tier: 'normal', baseMin: 3, baseMax: 8, stat: 'armorPen' },
  { id: 'phys-penet-e', name: '\u7834\u7532', type: 'prefix', tier: 'exceptional', baseMin: 8, baseMax: 18, stat: 'armorPen' },
  { id: 'phys-penet-l', name: '\u865a\u7a7a', type: 'prefix', tier: 'elite', baseMin: 18, baseMax: 35, stat: 'armorPen' },
  { id: 'phys-strike-suf-n', name: '\u6253\u51fb\u4e4b', type: 'suffix', tier: 'normal', baseMin: 4, baseMax: 10, stat: 'physDmgPct' },
  { id: 'phys-strike-suf-e', name: '\u529b\u91cf\u4e4b', type: 'suffix', tier: 'exceptional', baseMin: 10, baseMax: 22, stat: 'physDmgPct' },
  { id: 'phys-strike-suf-l', name: '\u6bc1\u706d\u4e4b', type: 'suffix', tier: 'elite', baseMin: 22, baseMax: 40, stat: 'physDmgPct' },
  { id: 'phys-punct-suf-n', name: '\u7a7f\u523a\u4e4b', type: 'suffix', tier: 'normal', baseMin: 5, baseMax: 10, stat: 'ignoreArmorPct' },
  { id: 'phys-punct-suf-e', name: '\u6495\u88c2\u4e4b', type: 'suffix', tier: 'exceptional', baseMin: 10, baseMax: 18, stat: 'ignoreArmorPct' },
  { id: 'phys-punct-suf-l', name: '\u5904\u51b3\u4eba\u4e4b', type: 'suffix', tier: 'elite', baseMin: 18, baseMax: 28, stat: 'ignoreArmorPct' },
]

export const SPELL_WEAPON_AFFIX_POOL = [
  { id: 'spell-glow-n', name: '\u5fae\u5149', type: 'prefix', tier: 'normal', baseMin: 2, baseMax: 6, stat: 'spellWeaponFlat' },
  { id: 'spell-glow-e', name: '\u8000\u773c', type: 'prefix', tier: 'exceptional', baseMin: 8, baseMax: 20, stat: 'spellWeaponFlat' },
  { id: 'spell-glow-l', name: '\u8d85\u51e1', type: 'prefix', tier: 'elite', baseMin: 20, baseMax: 45, stat: 'spellWeaponFlat' },
  { id: 'spell-focus-n', name: '\u4e13\u6ce8', type: 'prefix', tier: 'normal', baseMin: 2, baseMax: 4, stat: 'spellCritPct' },
  { id: 'spell-focus-e', name: '\u5171\u9e23', type: 'prefix', tier: 'exceptional', baseMin: 4, baseMax: 8, stat: 'spellCritPct' },
  { id: 'spell-focus-l', name: '\u539f\u521d', type: 'prefix', tier: 'elite', baseMin: 8, baseMax: 15, stat: 'spellCritPct' },
  { id: 'spell-over-n', name: '\u8fc7\u8f7d', type: 'prefix', tier: 'normal', baseMin: 4, baseMax: 10, stat: 'spellCritDmgPct' },
  { id: 'spell-over-e', name: '\u66b4\u98ce', type: 'prefix', tier: 'exceptional', baseMin: 10, baseMax: 22, stat: 'spellCritDmgPct' },
  { id: 'spell-over-l', name: '\u5929\u542f', type: 'prefix', tier: 'elite', baseMin: 22, baseMax: 40, stat: 'spellCritDmgPct' },
  { id: 'spell-confl-n', name: '\u6c47\u6d41', type: 'prefix', tier: 'normal', baseMin: 2, baseMax: 4, stat: 'manaRefluxPct' },
  { id: 'spell-confl-e', name: '\u548c\u58f0', type: 'prefix', tier: 'exceptional', baseMin: 4, baseMax: 8, stat: 'manaRefluxPct' },
  { id: 'spell-confl-l', name: '\u7ecf\u7ebf', type: 'prefix', tier: 'elite', baseMin: 8, baseMax: 14, stat: 'manaRefluxPct' },
  { id: 'spell-chan-n', name: '\u5f15\u5bfc', type: 'prefix', tier: 'normal', baseMin: 2, baseMax: 6, stat: 'manaOnCast' },
  { id: 'spell-chan-e', name: '\u6062\u590d', type: 'prefix', tier: 'exceptional', baseMin: 5, baseMax: 12, stat: 'manaOnCast' },
  { id: 'spell-chan-l', name: '\u660e\u5f7c', type: 'prefix', tier: 'elite', baseMin: 12, baseMax: 22, stat: 'manaOnCast' },
  { id: 'spell-star-n', name: '\u661f\u953b', type: 'prefix', tier: 'normal', baseMin: 4, baseMax: 10, stat: 'arcaneFollowup' },
  { id: 'spell-star-e', name: '\u6b8b\u50cf', type: 'prefix', tier: 'exceptional', baseMin: 10, baseMax: 22, stat: 'arcaneFollowup' },
  { id: 'spell-star-l', name: '\u65e5\u8680', type: 'prefix', tier: 'elite', baseMin: 22, baseMax: 45, stat: 'arcaneFollowup' },
  { id: 'spell-null-n', name: '\u65e0\u6548', type: 'prefix', tier: 'normal', baseMin: 3, baseMax: 8, stat: 'spellPen' },
  { id: 'spell-null-e', name: '\u7a7f\u900f', type: 'prefix', tier: 'exceptional', baseMin: 8, baseMax: 18, stat: 'spellPen' },
  { id: 'spell-null-l', name: '\u6df7\u6c79', type: 'prefix', tier: 'elite', baseMin: 18, baseMax: 35, stat: 'spellPen' },
  { id: 'spell-arc-suf-n', name: '\u5965\u672f\u4e4b', type: 'suffix', tier: 'normal', baseMin: 4, baseMax: 10, stat: 'spellDmgPct' },
  { id: 'spell-arc-suf-e', name: '\u6cd5\u672f\u4e4b', type: 'suffix', tier: 'exceptional', baseMin: 10, baseMax: 22, stat: 'spellDmgPct' },
  { id: 'spell-arc-suf-l', name: '\u6bc1\u706d\u4e4b', type: 'suffix', tier: 'elite', baseMin: 22, baseMax: 40, stat: 'spellDmgPct' },
  { id: 'spell-diss-suf-n', name: '\u6eb6\u89e3\u4e4b', type: 'suffix', tier: 'normal', baseMin: 5, baseMax: 10, stat: 'ignoreResistPct' },
  { id: 'spell-diss-suf-e', name: '\u8150\u5316\u4e4b', type: 'suffix', tier: 'exceptional', baseMin: 10, baseMax: 18, stat: 'ignoreResistPct' },
  { id: 'spell-diss-suf-l', name: '\u7834\u9635\u4e4b', type: 'suffix', tier: 'elite', baseMin: 18, baseMax: 28, stat: 'ignoreResistPct' },
]
